controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - arm_base_joint
      - upper_arm_joint
      - forearm_joint
      - wrist_joint
      - gripper_baseTOwrist_joint
      - gripper_base_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

gripper_controller:
  ros__parameters:
    joints:
      - right_prong_joint
      - left_prong_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity