moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - arm_base_joint
      - upper_arm_joint
      - forearm_joint
      - wrist_joint
      - gripper_baseTOwrist_joint
      - gripper_base_joint

  gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - right_prong_joint
      - left_prong_joint

trajectory_execution:
  manage_controllers: false
  allowed_execution_duration_scaling: 2.0
  allowed_goal_duration_margin: 1.0
  allowed_start_tolerance: 0.1